apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bedbug-nodejs 
  janus-idp.io/tekton: bedbug-nodejs
  backstage.io/kubernetes-id: bedbug-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bedbug-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  